import { Agent, I18nField, Status, MeetingData, DecisionEntry, ActionItemEntry, ActivityEntry } from '@/types'

export function tx(obj: I18nField | string | null | undefined, lang: string): string {
  if (!obj) return ''
  if (typeof obj === 'string') return obj
  const field = obj as I18nField
  return (field as unknown as Record<string, string>)[lang] ?? field.en ?? ''
}

export const STATUS_CONFIG: Record<Status, { dotVar: string; textVar: string; glowVar: string | null }> = {
  idle:       { dotVar: '--text-mute',  textVar: '--text-dim',  glowVar: null },
  thinking:   { dotVar: '--amber-soft', textVar: '--amber-soft',glowVar: '--amber-glow' },
  working:    { dotVar: '--amber',      textVar: '--amber',     glowVar: '--amber-glow' },
  'in-meeting':{ dotVar: '--purple',    textVar: '--purple',    glowVar: null },
  done:       { dotVar: '--green',      textVar: '--green',     glowVar: null },
}

export function sv(status: Status, kind: 'dotVar' | 'textVar' | 'glowVar'): string {
  const v = STATUS_CONFIG[status]?.[kind]
  return v ? `var(${v})` : 'transparent'
}

export const AGENTS: Agent[] = [
  { id:'pm-ming',    name:'PM_xiaoming',    emoji:'🧭', roleKey:'role.pm',
    specialty:{ en:'Roadmap, specs, prioritisation. Translates fuzzy ideas into shippable scope.',
                zh:'路线图、规格、优先级。把模糊的想法翻译成可交付的范围。' },
    status:'working',
    task:{ en:'Drafting Q3 roadmap for onboarding revamp', zh:'起草 Q3 新用户引导改版路线图' },
    tasks:142, avgMs:1840, joinedDays:128, tilt:-2.4 },
  { id:'dev-taro',   name:'dev_taro',       emoji:'⚙️', roleKey:'role.eng',
    specialty:{ en:'Full-stack TypeScript. Loves clean diffs, hates flaky tests.',
                zh:'全栈 TypeScript。喜欢干净的 diff，讨厌不稳定的测试。' },
    status:'thinking',
    task:{ en:'Reviewing PR #4421 — auth refactor', zh:'审阅 PR #4421— 鉴权重构' },
    tasks:208, avgMs:2110, joinedDays:204, tilt:1.6 },
  { id:'dz-luna',    name:'design_luna',    emoji:'✦',  roleKey:'role.design',
    specialty:{ en:'Systems thinker. Builds visual languages, ships pixel-perfect.',
                zh:'系统化思考。构建视觉语言，像素级交付。' },
    status:'working',
    task:{ en:'Iterating on Hive avatar hex states', zh:'迭代 Hive 头像六边形状态' },
    tasks:96,  avgMs:2640, joinedDays:88,  tilt:-1.2 },
  { id:'da-rio',     name:'data_rio',       emoji:'⌬',  roleKey:'role.data',
    specialty:{ en:'SQL, dashboards, north-star metrics. Asks "compared to what?"',
                zh:'SQL、看板、北极星指标。爱问"对比的是什么？"' },
    status:'in-meeting',
    task:{ en:'Pulling W18 retention cohorts', zh:'拉取 W18 留存数据' },
    tasks:71,  avgMs:1320, joinedDays:64,  tilt:2.8 },
  { id:'wr-sage',    name:'writer_sage',    emoji:'✎',  roleKey:'role.writer',
    specialty:{ en:'Voice & tone, docs, launch copy. Edits ruthlessly.',
                zh:'声调与文风、文档、发布文案。下笔狠。' },
    status:'idle', task:null,
    tasks:54,  avgMs:1980, joinedDays:42,  tilt:-2.9 },
  { id:'rs-kai',     name:'research_kai',   emoji:'◎',  roleKey:'role.research',
    specialty:{ en:'Interview synth, journey maps, opportunity sizing.',
                zh:'访谈综合、用户旅程、机会规模评估。' },
    status:'done',
    task:{ en:'Finished: 6-user diary study readout', zh:'已完成：6 位用户日记研究汇报' },
    tasks:38,  avgMs:3160, joinedDays:31,  tilt:1.9 },
  { id:'qa-owl',     name:'qa_owl',         emoji:'◉',  roleKey:'role.qa',
    specialty:{ en:'Test plans, edge cases, regression hunting.',
                zh:'测试计划、边缘情况、回归排查。' },
    status:'thinking',
    task:{ en:'Building test matrix for hex grid interactions', zh:'为六边形网格交互构建测试矩阵' },
    tasks:163, avgMs:1090, joinedDays:172, tilt:-2.1 },
  { id:'op-bee',     name:'ops_bee',        emoji:'⬡',  roleKey:'role.ops',
    specialty:{ en:'Procurement, vendor mgmt, internal tooling glue.',
                zh:'采购、供应商管理、内部工具粘合。' },
    status:'in-meeting',
    task:{ en:'Vendor sync — infra renewal', zh:'供应商对接 — 基础设施续约' },
    tasks:89,  avgMs:1520, joinedDays:96,  tilt:2.4 },
  { id:'mk-juno',    name:'market_juno',    emoji:'△',  roleKey:'role.growth',
    specialty:{ en:'Funnels, paid + organic, copywriting that converts.',
                zh:'漏斗、付费 + 自然增长、能转化的文案。' },
    status:'working',
    task:{ en:'A/B writing hero variants for landing v4', zh:'为落地页 v4 写 A/B 头图文案' },
    tasks:62,  avgMs:2230, joinedDays:51,  tilt:-1.8 },
  { id:'sl-finn',    name:'sales_finn',     emoji:'➤',  roleKey:'role.sales',
    specialty:{ en:'Discovery, demos, enterprise pipeline.',
                zh:'需求挖掘、演示、企业销售管线。' },
    status:'idle', task:null,
    tasks:44,  avgMs:1870, joinedDays:39,  tilt:2.1 },
  { id:'sp-iris',    name:'support_iris',   emoji:'✺',  roleKey:'role.support',
    specialty:{ en:'Tickets, runbooks, customer empathy.',
                zh:'工单、运行手册、客户同理心。' },
    status:'working',
    task:{ en:'Triaging 14 tickets in #urgent-queue', zh:'分流 #urgent-queue 中的 14 个工单' },
    tasks:312, avgMs:780,  joinedDays:215, tilt:-2.6 },
  { id:'sec-vega',   name:'sec_vega',       emoji:'⌖',  roleKey:'role.security',
    specialty:{ en:'Threat modelling, SOC2, audit prep.',
                zh:'威胁建模、SOC2、审计准备。' },
    status:'done',
    task:{ en:'Finished: dependency CVE sweep — 3 patched', zh:'已完成：依赖 CVE 扫描 — 修复 3 个' },
    tasks:47,  avgMs:1640, joinedDays:118, tilt:-2.4 },
  { id:'fn-orion',   name:'finance_orion',  emoji:'∮',  roleKey:'role.finance',
    specialty:{ en:'Budgeting, runway, board pack prep.',
                zh:'预算、现金流、董事会材料。' },
    status:'idle', task:null,
    tasks:28,  avgMs:2410, joinedDays:74,  tilt:1.4 },
]

export const ACTIVITY: ActivityEntry[] = [
  { t:'14:42:08', who:'dev_taro',
    verb:{ en:'finished thinking', zh:'结束思考' },
    detail:{ en:'PR #4421 — found 2 nits, 1 blocker', zh:'PR #4421 — 发现 2 处小问题、1 处阻塞' },
    tone:'thinking' },
  { t:'14:41:55', who:'support_iris',
    verb:{ en:'closed ticket', zh:'关闭工单' },
    detail:{ en:'#8821 → "billing question resolved"', zh:'#8821 → "账单问题已解决"' },
    tone:'done' },
  { t:'14:41:31', who:'design_luna',
    verb:{ en:'streaming output', zh:'正在输出' },
    detail:{ en:'hex card — variant 4 of 6', zh:'六边形卡片 — 4/6 变体' },
    tone:'working' },
  { t:'14:41:12', who:'data_rio',
    verb:{ en:'joined meeting', zh:'加入会议' },
    detail:{ en:'Q3 retention review (4 attending)', zh:'Q3 留存复盘（4 人参加）' },
    tone:'in-meeting' },
  { t:'14:40:58', who:'PM_xiaoming',
    verb:{ en:'assigned task', zh:'指派任务' },
    detail:{ en:'→ dev_taro: "audit /auth endpoints"', zh:'→ dev_taro：审计 /auth 接口' },
    tone:'working' },
]

export const MEETING: MeetingData = {
  topic: { en:'Q3 retention review — week 18 cohorts', zh:'Q3 留存复盘 — 第 18 周用户群' },
  startedAt: '14:38',
  attendees: ['da-rio', 'op-bee', 'pm-ming', 'rs-kai'],
  messages: [
    { from:'pm-ming', kind:'agent', t:'14:38',
      text:{ en:'Thanks for jumping on. Quick frame: retention dipped 2.4pts in W18. I want a hypothesis we can ship by Friday.',
             zh:'感谢大家上线。先简单框一下：W18 留存掉了 2.4 个百分点。我希望周五前能落地一个可以上线的假设。' } },
    { from:'da-rio',  kind:'agent', t:'14:38',
      text:{ en:'Looking at the cohort split now — pulling D7 / D14 / D28 side by side.',
             zh:'我正在看 cohort 拆分 — D7 / D14 / D28 并排拉一下。' } },
    { from:'da-rio',  kind:'agent', t:'14:39',
      text:{ en:'D7 is flat. D14 is where the drop concentrates — specifically free-tier users who hit the workspace limit.',
             zh:'D7 持平。D14 是下跌集中的地方 — 主要是触达工作区上限的免费用户。' } },
    { from:'rs-kai',  kind:'agent', t:'14:39',
      text:{ en:"That matches interviews 4 and 6. Users describe \"hitting a wall\" around day 10–14 and not knowing what to do next.",
             zh:'这和第 4、6 次访谈对得上。用户在第 10–14 天会"撞墙"，不知道下一步该做什么。' } },
    { from:'user',    kind:'user',  t:'14:40',
      text:{ en:'Is the wall the workspace cap specifically, or is it broader confusion about value?',
             zh:'这堵墙具体是工作区上限，还是对价值的更广泛困惑？' } },
    { from:'op-bee',  kind:'agent', t:'14:40',
      text:{ en:'On infra side — we did roll out a quota indicator in W17. Possible UX regression, but unlikely root cause.',
             zh:'从基础设施这边看 — W17 上线了配额指示器。可能是 UX 回归，但应该不是根因。' } },
    { from:'rs-kai',  kind:'agent', t:'14:41',
      text:{ en:"Broader value confusion. The cap is the symptom they verbalise, but underlying issue is they're not sure what to invite teammates for.",
             zh:'是更广泛的价值困惑。上限是他们表述出来的症状，但根本问题是他们不确定邀请同事来做什么。' } },
    { from:'pm-ming', kind:'agent', t:'14:41',
      text:{ en:"Okay. Proposal: ship a contextual nudge at D10 — \"here's what your team could do next\" — measuring D14 + D28 lift.",
             zh:'好。提议：在 D10 推一个情境化提示 — "你的团队接下来可以做这些" — 用 D14 + D28 提升来衡量。' },
      streaming:true },
  ],
}

export const DECISIONS: DecisionEntry[] = [
  { en:"D14 retention drop is concentrated in free-tier users hitting workspace limit, but root cause is broader value confusion (verified by research_kai's interviews).",
    zh:'D14 留存下跌集中在触达工作区上限的免费用户身上，但根因是更广泛的价值困惑（研究 kai 的访谈已验证）。' },
]

export const ACTION_ITEMS: ActionItemEntry[] = [
  { who:'design_luna', text:{ en:'Mock D10 nudge — 2 variants', zh:'D10 提示稿 — 2 个版本' } },
  { who:'data_rio',    text:{ en:'Define D14+D28 lift metric',   zh:'定义 D14+D28 提升指标' } },
  { who:'dev_taro',    text:{ en:'Scope feature flag rollout',    zh:'梳理灰度发布范围' } },
]
